îº§ Environment updated. Reloading shell...
2025-10-28 09:26:10,018 - pyrogram.crypto.aes - INFO - Using TgCrypto
2025-10-28 09:26:10,117 - asyncio - DEBUG - Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/runner/workspace/bot.py", line 38, in <module>
    app.run()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vnvdzw4182wb2ifzi0cczhv80yfnpx1q-python3-3.12.11/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/utilities/start.py", line 74, in start
    await self.initialize()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/auth/initialize.py", line 46, in initialize
    self.load_plugins()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/client.py", line 689, in load_plugins
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vnvdzw4182wb2ifzi0cczhv80yfnpx1q-python3-3.12.11/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/runner/workspace/plugins/youtube_dl_echo.py", line 10, in <module>
    import lk21, urllib.parse, filetype, shutil, time, tldextract, asyncio, json, math, os, requests
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/lk21/__init__.py", line 11, in <module>
    from .cli import main
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/lk21/cli.py", line 2, in <module>
    from .thirdparty.exrex import generate as generate_strings
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/lk21/thirdparty/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/nix/store/vnvdzw4182wb2ifzi0cczhv80yfnpx1q-python3-3.12.11/lib/python3.12/re/__init__.py)
